project:
  type: website

website:
  title: "react_tables" 
  navbar:
    left:
      - text: Get Started
        file: get-started/index.qmd
      - text: Examples
        file: examples/index.qmd
      - text: Demos
        menu: 
          - demos/twitter-followers.qmd
          - demos/great-tables.qmd
      - text: Articles
        menu:
          - articles/custom-rendering.qmd
      - text: Reference
        file: reference/index.qmd
      #- href: reference/index.qmd
      #  text: Reference
    right:
      - icon: github
        href: https://github.com/machow/bigblock
      #- icon: rss
      #  href: blog/index.xml
# tell quarto to read the generated sidebar
#metadata-files:
#  - _sidebar.yml

format:
  html:
    toc: true

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: react_tables

  # write sidebar data to this file
  sidebar: _sidebar.yml

  sections:
    - title: Some functions
      desc: Functions to inspect docstrings.
      contents:
        # the functions being documented in the package.
        # you can refer to anything: class methods, modules, etc..
        - Reactable